export default {
    content: ['./index.html', './src/**/*.{ts,tsx}'],
    theme: {
        extend: {
            colors: {
                canvas: '#fffaf0',
                'surface-soft': '#faf5e8',
                'surface-card': '#f5f0e0',
                'surface-strong': '#ebe6d6',
                'surface-dark': '#0a1a1a',
                'surface-dark-elevated': '#1a2a2a',
                hairline: '#e5e5e5',
                ink: '#0a0a0a',
                'body-strong': '#1a1a1a',
                body: '#3a3a3a',
                muted: '#6a6a6a',
                'muted-soft': '#9a9a9a',
                'on-primary': '#ffffff',
                brand: {
                    pink: '#ff4d8b',
                    teal: '#1a3a3a',
                    lavender: '#b8a4ed',
                    peach: '#ffb084',
                    ochre: '#e8b94a',
                    mint: '#a4d4c5',
                    coral: '#ff6b5a',
                },
                success: '#22c55e',
                warning: '#f59e0b',
                error: '#ef4444',
            },
            fontFamily: {
                display: ['"Inter Variable"', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
                sans: ['"Inter Variable"', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
            },
            fontSize: {
                'display-xl': ['72px', { lineHeight: '1', letterSpacing: '-0.0347em', fontWeight: '500' }],
                'display-lg': ['56px', { lineHeight: '1.05', letterSpacing: '-0.0357em', fontWeight: '500' }],
                'display-md': ['40px', { lineHeight: '1.1', letterSpacing: '-0.025em', fontWeight: '500' }],
                'display-sm': ['32px', { lineHeight: '1.15', letterSpacing: '-0.015em', fontWeight: '500' }],
                'title-lg': ['24px', { lineHeight: '1.3', letterSpacing: '-0.0125em', fontWeight: '600' }],
                'title-md': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
                'title-sm': ['16px', { lineHeight: '1.4', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '1.55' }],
                'body-sm': ['14px', { lineHeight: '1.55' }],
                caption: ['13px', { lineHeight: '1.4', fontWeight: '500' }],
                'caption-up': ['12px', { lineHeight: '1.4', letterSpacing: '0.125em', fontWeight: '600' }],
                button: ['14px', { lineHeight: '1', fontWeight: '600' }],
                nav: ['14px', { lineHeight: '1.4', fontWeight: '500' }],
            },
            spacing: {
                xxs: '4px',
                xs: '8px',
                sm: '12px',
                md: '16px',
                lg: '24px',
                xl: '32px',
                xxl: '48px',
                section: '96px',
            },
            borderRadius: {
                xs: '6px',
                sm: '8px',
                md: '12px',
                lg: '16px',
                xl: '24px',
                pill: '9999px',
            },
            maxWidth: {
                content: '1280px',
            },
        },
    },
    plugins: [],
};
